Add more examples of filter operations
dbmdz/digitalcollections-model pull request #168
Opened 2020-09-29 07:57 UTC by morpheus-87

2020-09-29 11:23 UTC, datazuul requested changes

2020-09-29 11:23 UTC, datazuul commented on dc-model/src/main/java/de/digitalcollections/model/api/filter/enums/FilterOperation.java
> + * <tr><td>eq    </td><td> Equals                   </td><td>city=eq:Munich / publicationDate=lte:2020-01-01      </td></tr>
"lte" überall ist wohl falsch

2020-09-29 11:38 UTC, morpheus-87 commented on dc-model/src/main/java/de/digitalcollections/model/api/filter/enums/FilterOperation.java
> + * <tr><td>eq    </td><td> Equals                   </td><td>city=eq:Munich / publicationDate=lte:2020-01-01      </td></tr>
Danke für den Hinweis, ist korrigiert.

2020-09-30 13:33 UTC, datazuul approved these changes

2020-09-30 13:34 UTC, merged