WIP: Breaking changes version 9.0.0-SNAPSHOT
dbmdz/digitalcollections-model pull request #211
Opened 2021-02-15 15:59 UTC by datazuul

2021-02-17 16:42 UTC, jbaiter commented on dc-model-jackson/src/test/resources/serializedTestObjects/filter/Filtering.json
> +  "filterCriteria" : [ {
Ist das so die Datenstruktur die Clients für das Filtering zusammenbauen müssen?

2021-02-19 12:50 UTC, datazuul commented on dc-model-jackson/src/test/resources/serializedTestObjects/filter/Filtering.json
> +  "filterCriteria" : [ {
ja. für java-anwendungen gibt es dafür natürlich einen fluent builder

2021-02-19 13:11 UTC, datazuul commented on dc-model-jackson/src/test/resources/serializedTestObjects/filter/Filtering.json
> +  "filterCriteria" : [ {
für direkte url-abfragen gibt es die url-syntax... das obige ist teil eines serialisierten pagerequest-objektes, das viele bestandteile hat

2021-02-19 14:06 UTC, jbaiter commented on dc-model-jackson/src/test/resources/serializedTestObjects/filter/Filtering.json
> +  "filterCriteria" : [ {
Ist halt *extrem* java-ig von der API. Da kann man im Prirnzip gleich `Object.serialize` nehmen :see_no_evil: 
Gibt's keine Möglichkeit die Daten sauber nach ISO zu formatieren, das `long`-typing rauszunehmen, etc?

2021-02-22 07:13 UTC, datazuul commented on dc-model-jackson/src/test/resources/serializedTestObjects/filter/Filtering.json
> +  "filterCriteria" : [ {
dazu gibt es bereits seit längerem ein ticket: https://gitlab.lrz.de/mdz/webapps/internal/cudami/webapp/-/issues/17

2021-03-01 13:14 UTC, morpheus-87 requested changes

2021-03-01 13:14 UTC, morpheus-87 commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/security/UserMixIn.java
> +// @JsonSubTypes({@JsonSubTypes.Type(value = User.class)})
Können die beiden Zeilen raus?

2021-03-01 13:14 UTC, morpheus-87 commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/text/contentblock/AttributesMixIn.java
> -package de.digitalcollections.model.jackson.mixin.identifiable.parts.structuredcontent.contentblocks;
Kann die Datei eventuell ganz raus? Die Modellklasse gibts ja nicht mehr.

2021-03-01 13:26 UTC, datazuul commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/DigitalCollectionsModelModule.java
> -    context.setMixInAnnotations(Translation.class, TranslationMixIn.class);
wird nicht verwendet

2021-03-01 13:28 UTC, datazuul commented on dc-model-xml/pom.xml
> -    <version>8.2.1</version>
war in der projektansicht schon aus den modules raus. hab nun in file-ansicht das unterverzeichnis explizit gelöscht

2021-03-01 13:28 UTC, datazuul commented on dc-model-feign/pom.xml
> -    <version>8.2.1</version>
war in der projektansicht schon aus den modules raus. hab nun in file-ansicht das unterverzeichnis explizit gelöscht

2021-03-01 13:30 UTC, datazuul commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/security/UserMixIn.java
> +// @JsonSubTypes({@JsonSubTypes.Type(value = User.class)})
raus

2021-03-01 13:34 UTC, datazuul commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/text/contentblock/AttributesMixIn.java
> -package de.digitalcollections.model.jackson.mixin.identifiable.parts.structuredcontent.contentblocks;
wird aber von anderen mixins extended. habe es umbenannt nach ContentBlockWithAttributesMixIn

2021-03-01 15:28 UTC, morpheus-87 approved these changes

2021-03-01 15:37 UTC, merged