Draft: Remove FilterValuePlaceholder as this has to be handled different in …
dbmdz/digitalcollections-model pull request #256
Opened 2021-09-10 12:32 UTC by datazuul

…using system

2021-09-16 09:22 UTC, morpheus-87 approved these changes

2021-09-17 10:27 UTC, daforster requested changes

2021-09-17 10:27 UTC, daforster commented on dc-model/src/main/java/de/digitalcollections/model/filter/FilterCriterion.java
> + *   <li>a flag to indicate if expression has to be nativeExpression or be used unchanged in
```suggestion
 *   <li>a flag to indicate if expression has to be mapped or be used unchanged in
```

2021-09-17 10:27 UTC, daforster commented on dc-model/src/main/java/de/digitalcollections/model/filter/FilterCriterion.java
> + *       underlying backend system (e.g. mapping Java member names to database column names; no
```suggestion
 *       underlying backend system (e.g. mapping Java member names to database column names vs. no
```
Just to point it out more precisely

2021-09-17 10:27 UTC, daforster commented on dc-model/src/main/java/de/digitalcollections/model/filter/FilterCriterion.java
> +   * @param nativeExpression a flag to indicate if expression has to be nativeExpression or should
```suggestion
   * @param nativeExpression a flag to indicate if expression has to be mapped or should
```
I guess it was changed by the IDE when renaming the field

2021-09-17 10:27 UTC, daforster commented on dc-model/src/main/java/de/digitalcollections/model/filter/FilterCriterion.java
> +  public void setFieldName(String expression) {
```suggestion
  @Deprecated
    public void setFieldName(String expression) {
```

2021-09-17 11:30 UTC, clorenz approved these changes

2021-09-17 11:37 UTC, daforster approved these changes

2021-09-17 11:37 UTC, merged