Convenience method for url aliases
dbmdz/digitalcollections-model pull request #304
Opened 2022-03-14 13:30 UTC by morpheus-87

2022-03-14 14:09 UTC, daforster requested changes

2022-03-15 07:21 UTC, datazuul commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/Identifiable.java
> +        localizedUrlAliases.get(Locale.forLanguageTag(locale.getLanguage()));
nein. beispiel: "de_DE" wird dadurch zu "de" und danach zu einem Locale.GERMAN. ist ein unterschied

2022-03-15 07:46 UTC, datazuul commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/Identifiable.java
> +  /**
documentation added

2022-03-15 08:00 UTC, datazuul approved these changes

2022-03-15 09:23 UTC, daforster requested changes

2022-03-15 09:23 UTC, daforster commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/Identifiable.java
> +    Stream<UrlAlias> primaries = urlAliases.stream().filter(UrlAlias::isPrimary);
```suggestion
    Stream<UrlAlias> primaries = urlAliases.stream().filter(u -> u.isPrimary());
```

2022-03-15 10:26 UTC, daforster approved these changes

2022-03-15 10:33 UTC, merged