Publication -> Publisher
dbmdz/digitalcollections-model pull request #401
Opened 2022-10-27 12:54 UTC by clorenz

Renamed (and refactored) `Publication` to `Publisher` in context of `Manifestation`

2022-10-27 13:06 UTC, daforster requested changes

2022-10-27 13:06 UTC, daforster commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/work/Publisher.java
> +        && Objects.equals(agent, that.agent)
```suggestion
    return super.equals(that)
        && Objects.equals(locations, that.locations)
        && Objects.equals(agent, that.agent)
```

2022-10-27 13:06 UTC, daforster commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/work/Publisher.java
> +    return Objects.hash(locations, agent, publisherPresentation);
```suggestion
    return Objects.hash(locations, agent, publisherPresentation) + super.hashCode() + 330;
```

2022-11-02 09:13 UTC, clorenz commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/work/Publisher.java
> +        && Objects.equals(agent, that.agent)
ist eingebaut

2022-11-02 09:14 UTC, clorenz commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/work/Publisher.java
> +    return Objects.hash(locations, agent, publisherPresentation);
ist eigebaut

2022-11-02 11:01 UTC, daforster approved these changes

2022-11-02 11:04 UTC, merged