Draft: Three kinds of publishers
dbmdz/digitalcollections-model pull request #412
Opened 2022-11-28 14:55 UTC by clorenz

2022-11-30 14:39 UTC, daforster commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/manifestation/Publisher.java
> +      String publisherPresentation,
```suggestion
```

2022-11-30 15:04 UTC, clorenz commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/manifestation/Publisher.java
> +      String publisherPresentation,
Danke, ist jetzt entfernt ;)

2022-11-30 16:23 UTC, datazuul commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/ProductionInfoMixIn.java
> +@JsonDeserialize(as = PublishingInfo.class)
```suggestion
@JsonDeserialize(as = ProductionInfo.class)
```

2022-11-30 16:29 UTC, datazuul requested changes

2022-11-30 16:29 UTC, datazuul commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/DistributionInfoMixIn.java
> +@JsonDeserialize(as = DistributionInfo.class)
kann doch gar nicht kompilieren? im model gibt es keine DistributionInfo-Klasse!?

2022-11-30 16:29 UTC, datazuul commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/PublicationInfoMixIn.java
> +@JsonDeserialize(as = PublicationInfo.class)
kann doch gar nicht kompilieren? im model gibt es keine PublicationInfo-Klasse!?

2022-12-01 11:08 UTC, clorenz commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/ProductionInfoMixIn.java
> +@JsonDeserialize(as = PublishingInfo.class)
ist gefixed

2022-12-01 11:08 UTC, clorenz commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/DistributionInfoMixIn.java
> +@JsonDeserialize(as = DistributionInfo.class)
ist gefixed

2022-12-01 11:08 UTC, clorenz commented on dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/PublicationInfoMixIn.java
> +@JsonDeserialize(as = PublicationInfo.class)
ist gefixed

2022-12-01 11:54 UTC, datazuul requested changes

2022-12-01 11:54 UTC, datazuul commented on CHANGELOG.md
> +<<<<<<< HEAD
hier ist noch ein merge-problem

2022-12-01 11:54 UTC, datazuul commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/manifestation/Manifestation.java
> +  public PublishingInfo getPublicationInfo() {
typspezifisch zurückgeben...

2022-12-01 11:54 UTC, datazuul commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/manifestation/Manifestation.java
> +  public PublishingInfo getDistributionInfo() {
typspezifisch zurückgeben...

2022-12-01 11:54 UTC, datazuul commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/manifestation/Manifestation.java
> +  public PublishingInfo getProductionInfo() {
typspezifisch zurückgeben...

2022-12-01 12:11 UTC, clorenz commented on CHANGELOG.md
> +<<<<<<< HEAD
Ist gefixed

2022-12-01 12:11 UTC, clorenz commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/manifestation/Manifestation.java
> +  public PublishingInfo getPublicationInfo() {
gefixed

2022-12-01 12:11 UTC, clorenz commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/manifestation/Manifestation.java
> +  public PublishingInfo getDistributionInfo() {
gefixed

2022-12-01 12:11 UTC, clorenz commented on dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/manifestation/Manifestation.java
> +  public PublishingInfo getProductionInfo() {
gefixed

2022-12-01 12:22 UTC, datazuul approved these changes

2022-12-01 12:23 UTC, merged